edit disabled explorer filter bar text PEDS-868
chicagopcdc/data-portal pull request #468
Opened 2022-10-18 15:19 UTC by grugna

Description about what this pull request does.

Please make sure to follow the [DEV guidelines](https://gen3.org/resources/developer/dev-introduction/) before asking for review.

### New Features

- Implemented XXX

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes

2022-10-18 23:02 UTC, bobaekang requested changes
Thanks for requesting my review on the change @grugna. I think the revised text has some improvements as well as some regressions. I'd like to suggest the following as the synthesis between the original & the changed:

> This feature is disabled when the active Filter Set has a composed filter state. To re-enable it, go to Filter Set Workspace and use (activate) a Filter Set with a standard (non-composed) filter state or create a new one.

2022-10-21 13:44 UTC, grugna commented
I inverted the two sentences you suggested because Suzi wanted the action to come before the description since she pointed out many people may not read all of it.
`To re-enable it, go to Filter Set Workspace and use (activate) a Filter Set with a standard (non-composed) filter state or create a new one. This feature is disabled when the active Filter Set has a composed filter state.`

2022-10-21 23:07 UTC, bobaekang commented
@grugna That makes sense.

In that case, I have one last small suggestion (italicization for emphasis only) for clarification: 

> To re-enable _this feature_, go to Filter Set Workspace and use (activate) a Filter Set with a standard (non-composed) filter state or create a new one. _The feature_ is disabled when the active Filter Set has a composed filter state.

Please feel free to merge with this change. 😄

2022-10-21 23:07 UTC, bobaekang approved these changes

2022-10-27 15:39 UTC, merged